language: node_js
node_js:
  - 10
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_install:
  - npm install
  - export NODE_ENV=production
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u root --password="root"
  - sudo service mysql restart
  - mysql -u root --password="root" < test/travis.sql
script:
  - npm run test
