language: node_js
node_js:	node_js:
  - 8	  - 8
services:
  - mysql
before_install:	before_install:
  - npm install	  - npm install
  - export NODE_ENV=production	  - export NODE_ENV=production
  - mysql -u root --password="" < test/travis.sql
script:	script:
  - npm run test 	  - npm run test 